# Этап 1: Сборка клиента
FROM node:24-alpine AS client-builder
WORKDIR /app/client
COPY client/package.json client/package-lock.json ./
RUN npm ci
COPY client/ .
RUN npm run build

# Этап 2: Финальный nginx образ
FROM nginx:alpine

# Создаем папку для letsencrypt
RUN mkdir -p /var/www/letsencrypt/.well-known/acme-challenge

COPY --from=client-builder /app/client/dist /usr/share/nginx/html
COPY nginx/prod.conf /etc/nginx/nginx.conf

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]